### ISSUE TITLE
Embed MIDI file into a .synthesia

### ISSUE THREAD

**Issue by Noxalus** [Synthesia-LLC/metadata-editor#1]
Hello,

According to the documentation, the .synthesia metadata file "must either be in one of the folders scanned by Synthesia or in the same directory as the song you're playing". 

But it would be great to have all information needed by Synthesia in a single file only, including MIDI data. Is it something planned in the future ?

**Comment by npiegdon** [comment]
There are already so many different (good!) container formats that I'd prefer to avoid creating a new one.

The closest things will get to this will be using something like adding support to Synthesia for reading [Open Score Format](http://openscoreformat.sourceforge.net/) files.  Those can store the MIDI, (optional MusicXML, PDF, etc. versions of the song), and the associated .synthesia file all inside one container.

That way, instead of creating some new proprietary format, other OSF-enabled software would be able to use as much or as little of the contents as they like (most-likely ignoring the .synthesia file, but using the rest).  That is a nice story for compatibility.

I could see adding an OSF export option to the metadata editor some day to bundle a MIDI and metadata file together, but the song wouldn't technically be embedded _inside_ the metadata.  So, I'll close this.
